[package]
name = "torrents-csv-service"
version = "0.1.0"
authors = ["Heretic <tylerjobsearch06@gmx.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
actix-files = "0.5.0"
env_logger = "0.8.2"

serde = "1.0.118"
serde_json = "1.0.61"
serde_derive = "1.0.118"

futures = "0.3.8"
failure = "0.1.8"

r2d2 = "0.8.9"
r2d2_sqlite = "0.17.0"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
